# Default profile: in-memory H2 (quick dev)
spring:
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  thymeleaf:
    cache: false

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG

---
# MySQL profile: run with --spring.profiles.active=mysql
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/indigenous?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Windhoek
    username: indigenous
    password: indigenous
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
